name: Latest unstable build

on: 
  push:
    #branches:
      #- develop

jobs:
   createWindowsGameBuild:
     name: Create latest build artifact for Windows
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore nuget packages
         run: dotnet restore
         shell: powershell
       - name: Build project Windows
         run: dotnet publish -c Release -r win-x64 --self-contained true
         shell: powershell
       - name: Move successful build
         run: |
          mkdir artifact/
          mv .\src\Tank\bin\Release\**\win-x64\publish artifact/LastStable
          mv ./src/Tank/bin/Release
       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with:
          name: WindowsGameBuildArtifact
          path: |
            artifact/
   createLinuxGameBuild:
     name: Create latest build artifact for Linux
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore nuget packages
         run: dotnet restore
         shell: powershell
       - name: Build project Linux
         run: dotnet publish -c Release -r linux-x64 --self-contained true
         shell: powershell
       - name: Move successful build
         run: |
          mkdir artifact/
          mv .\src\Tank\bin\Release\**\linux-x64\publish artifact/LastStable
          mv ./src/Tank/bin/Release
       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with:
          name: LinuxGameBuildArtifact
          path: |
            artifact/   
   createMacOsGameBuild:
     name: Create latest build artifact for MacOs
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore nuget packages
         run: dotnet restore
         shell: powershell
       - name: Build project MacOs
         run: dotnet publish -c Release -r osx-x64 --self-contained true
         shell: powershell
       - name: Move successful build
         run: |
          mkdir artifact/
          mv .\src\Tank\bin\Release\**\osx-x64\publish artifact/LastStable
          mv ./src/Tank/bin/Release
       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with:
          name: MacOsGameBuildArtifact
          path: |
            artifact/
   createWindowsGameZip:
     name: Create Windows zip
     needs: ["createWindowsGameBuild"]
     runs-on: ubuntu-latest   
     steps:
       - name: Download artifacts
         uses: actions/download-artifact@v2
         with:
           name: WindowsGameBuildArtifact
           path: dist
       - name: Create zip
         run: |
           cd dist/
           zip -r Latest_WindowsGameArtifact.zip .
       - name: Move artifact
         run: |
           mkdir upload-artifacts/
           mv dist/Latest_WindowsGameArtifact.zip upload-artifacts/
       - name: Upload build artifact
         uses: actions/upload-artifact@v2
         with:
          name: WindowsGameArtifact
          path: |
            upload-artifacts/
   createLinuxGameZip:
     name: Create Linux zip
     needs: ["createLinuxGameBuild"]
     runs-on: ubuntu-latest   
     steps:
       - name: Download artifacts
         uses: actions/download-artifact@v2
         with:
           name: LinuxGameBuildArtifact
           path: dist
       - name: Create zip
         run: |
           cd dist/
           zip -r Latest_LinuxGameArtifact.zip .
       - name: Move artifact
         run: |
           mkdir upload-artifacts/
           mv dist/Latest_LinuxGameArtifact.zip upload-artifacts/
       - name: Upload build artifact
         uses: actions/upload-artifact@v2
         with:
          name: LinuxGameArtifact
          path: |
            upload-artifacts/
   createMacOsGameZip:
     name: Create MacOs zip
     needs: ["createMacOsGameBuild"]
     runs-on: ubuntu-latest   
     steps:
       - name: Download artifacts
         uses: actions/download-artifact@v2
         with:
           name: MacOsGameBuildArtifact
           path: dist
       - name: Create zip
         run: |
           cd dist/
           zip -r Latest_MacOsGameArtifact.zip .
       - name: Move artifact
         run: |
           mkdir upload-artifacts/
           mv dist/Latest_MacOsGameArtifact.zip upload-artifacts/
       - name: Upload build artifact
         uses: actions/upload-artifact@v2
         with:
          name: MacOsGameArtifact
          path: |
            upload-artifacts/
   createUnstableReleaseAndUploadArtifacts:
     name: Upload last unstable
     needs: ["createWindowsGameZip", "createLinuxGameZip", "createMacOsGameZip"]
     runs-on: ubuntu-latest
     steps:
       - name: Download Windows artifact
         uses: actions/download-artifact@v2
         with:
           name: WindowsGameArtifact
           path: releases
       - name: Download Linux artifact
         uses: actions/download-artifact@v2
         with:
           name: LinuxGameArtifact
           path: releases
       - name: Download MacOs artifact
         uses: actions/download-artifact@v2
         with:
           name: MacOsGameArtifact
           path: releases
       - name: Read folder content
         run: ls -la releases
       - name: Get release name
         id: getReleaseName
         run: echo ::set-output name=RELEASE_NAME::${GITHUB_REF/refs\/tags\//}-${GITHUB.RUN_NUMBER}  
       - name: Create last unstable Release
         uses: softprops/action-gh-release@v1
         with:
           name: Latest unstable
           body: This is the latest unstable build version, feel free to test it out. Most of the time only the windows build got tested!
           tag_name: ${{ steps.getReleaseName.outputs.RELEASE_NAME }}
           draft: false
           prerelease: true
           files: releases/**.zip
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  