name: Check pull request

on: [pull_request]

jobs:
   checkGameBuild:
     name: Check build
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore
         run: dotnet restore
         shell: powershell
       - name: Build project Windows
         run: dotnet publish -c Release -r win-x64 --self-contained true
         shell: powershell