name: Check pull request

on: push
#[pull_request]

jobs:
   checkWindowsGameBuild:
     name: Check build for Windows
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore
         run: dotnet restore
         shell: powershell
       - name: Set Version
         run: |
          echo latest-test-build-${GITHUB.RUN_NUMBER}
          echo latest-test-build-${GITHUB.RUN_NUMBER} > .\src\Tank\Assets\Resources\Version.txt
          cat .\src\Tank\Assets\Resources\Version.txt
         shell: powershell
       - name: Build project Windows
         run: dotnet publish -c Release -r win-x64 --self-contained true
         shell: powershell
   checkLinuxGameBuild:
     name: Check build for Linux
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore
         run: dotnet restore
         shell: powershell
       - name: Set Version
         run: |
          echo latest-test-build-${GITHUB.RUN_NUMBER}
          echo latest-test-build-${GITHUB.RUN_NUMBER} > .\src\Tank\Assets\Resources\Version.txt
          cat .\src\Tank\Assets\Resources\Version.txt
         shell: powershell
       - name: Build project Linux
         run: dotnet publish -c Release -r linux-x64 --self-contained true
         shell: powershell
   checkDarwinGameBuild:
     name: Check build for MacOs
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore
         run: dotnet restore
         shell: powershell
       - name: Set Version
         run: |
          echo latest-test-build-${GITHUB.RUN_NUMBER}
          echo latest-test-build-${GITHUB.RUN_NUMBER} > .\src\Tank\Assets\Resources\Version.txt
          cat .\src\Tank\Assets\Resources\Version.txt
         shell: powershell  
       - name: Build project Mac OS
         run: dotnet publish -c Release -r osx-x64 --self-contained true
         shell: powershell