name: Check pull request

on: 
    push #[pull_request]

jobs:
   checkWindowsGameBuild:
     name: Check build
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore
         run: dotnet restore
         shell: powershell
       - name: Build project Windows
         run: dotnet publish -c Release -r win-x64 --self-contained true
         shell: powershell
   checkLinuxGameBuild:
     name: Check build
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore
         run: dotnet restore
         shell: powershell
       - name: Build project Linux
         run: dotnet publish -c Release -r linux-x64 --self-contained true
         shell: powershell
   checkDarwinGameBuild:
     name: Check build
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Restore
         run: dotnet restore
         shell: powershell
       - name: Build project Mac OS
         run: dotnet publish -c Release -r osx-x64 --self-contained true
         shell: powershell